package pe.edu.sistemas.dao.domain;

// Generated 05/11/2016 12:55:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Asistencia generated by hbm2java
 */
@Entity
@Table(name = "asistencia")
public class Asistencia implements java.io.Serializable {

	private int idAsistencia;
	private HorarioCurso horarioCurso;
	private Date feRegistro;
	private String tipoAsistencia;
	private Set asistenciaDetalles = new HashSet(0);

	public Asistencia() {
	}

	public Asistencia(int idAsistencia) {
		this.idAsistencia = idAsistencia;
	}

	public Asistencia(int idAsistencia, HorarioCurso horarioCurso,
			Date feRegistro, String tipoAsistencia, Set asistenciaDetalles) {
		this.idAsistencia = idAsistencia;
		this.horarioCurso = horarioCurso;
		this.feRegistro = feRegistro;
		this.tipoAsistencia = tipoAsistencia;
		this.asistenciaDetalles = asistenciaDetalles;
	}

	@Id
	@Column(name = "id_asistencia", unique = true, nullable = false)
	public int getIdAsistencia() {
		return this.idAsistencia;
	}

	public void setIdAsistencia(int idAsistencia) {
		this.idAsistencia = idAsistencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_horario_curso")
	public HorarioCurso getHorarioCurso() {
		return this.horarioCurso;
	}

	public void setHorarioCurso(HorarioCurso horarioCurso) {
		this.horarioCurso = horarioCurso;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fe_registro", length = 13)
	public Date getFeRegistro() {
		return this.feRegistro;
	}

	public void setFeRegistro(Date feRegistro) {
		this.feRegistro = feRegistro;
	}

	@Column(name = "tipo_asistencia", length = 3)
	public String getTipoAsistencia() {
		return this.tipoAsistencia;
	}

	public void setTipoAsistencia(String tipoAsistencia) {
		this.tipoAsistencia = tipoAsistencia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asistencia")
	public Set getAsistenciaDetalles() {
		return this.asistenciaDetalles;
	}

	public void setAsistenciaDetalles(Set asistenciaDetalles) {
		this.asistenciaDetalles = asistenciaDetalles;
	}

}
