package pe.edu.sistemas.dao.domain;

// Generated 05/11/2016 12:55:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "docente")
public class Docente implements java.io.Serializable {

	private int idDocente;
	private String codDocente;
	private String numDni;
	private String nomDocente;
	private String apePaterno;
	private String apeMaterno;
	private Date feNacimi;
	private String email;
	private String claveSistema;
	private Set horarioCursos = new HashSet(0);
	private Set fotos = new HashSet(0);

	public Docente() {
	}

	public Docente(int idDocente) {
		this.idDocente = idDocente;
	}

	public Docente(int idDocente, String codDocente, String numDni,
			String nomDocente, String apePaterno, String apeMaterno,
			Date feNacimi, String email, String claveSistema,
			Set horarioCursos, Set fotos) {
		this.idDocente = idDocente;
		this.codDocente = codDocente;
		this.numDni = numDni;
		this.nomDocente = nomDocente;
		this.apePaterno = apePaterno;
		this.apeMaterno = apeMaterno;
		this.feNacimi = feNacimi;
		this.email = email;
		this.claveSistema = claveSistema;
		this.horarioCursos = horarioCursos;
		this.fotos = fotos;
	}

	@Id
	@Column(name = "id_docente", unique = true, nullable = false)
	public int getIdDocente() {
		return this.idDocente;
	}

	public void setIdDocente(int idDocente) {
		this.idDocente = idDocente;
	}

	@Column(name = "cod_docente", length = 15)
	public String getCodDocente() {
		return this.codDocente;
	}

	public void setCodDocente(String codDocente) {
		this.codDocente = codDocente;
	}

	@Column(name = "num_dni", length = 15)
	public String getNumDni() {
		return this.numDni;
	}

	public void setNumDni(String numDni) {
		this.numDni = numDni;
	}

	@Column(name = "nom_docente", length = 35)
	public String getNomDocente() {
		return this.nomDocente;
	}

	public void setNomDocente(String nomDocente) {
		this.nomDocente = nomDocente;
	}

	@Column(name = "ape_paterno", length = 35)
	public String getApePaterno() {
		return this.apePaterno;
	}

	public void setApePaterno(String apePaterno) {
		this.apePaterno = apePaterno;
	}

	@Column(name = "ape_materno", length = 35)
	public String getApeMaterno() {
		return this.apeMaterno;
	}

	public void setApeMaterno(String apeMaterno) {
		this.apeMaterno = apeMaterno;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fe_nacimi", length = 13)
	public Date getFeNacimi() {
		return this.feNacimi;
	}

	public void setFeNacimi(Date feNacimi) {
		this.feNacimi = feNacimi;
	}

	@Column(name = "email", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "clave_sistema", length = 30)
	public String getClaveSistema() {
		return this.claveSistema;
	}

	public void setClaveSistema(String claveSistema) {
		this.claveSistema = claveSistema;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
	public Set getHorarioCursos() {
		return this.horarioCursos;
	}

	public void setHorarioCursos(Set horarioCursos) {
		this.horarioCursos = horarioCursos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
	public Set getFotos() {
		return this.fotos;
	}

	public void setFotos(Set fotos) {
		this.fotos = fotos;
	}

}
