package pe.edu.sistemas.dao.domain;

// Generated 05/11/2016 12:55:23 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Foto generated by hbm2java
 */
@Entity
@Table(name = "foto")
public class Foto implements java.io.Serializable {

	private int idFoto;
	private Docente docente;
	private String nomRuta;
	private Boolean blEstado;

	public Foto() {
	}

	public Foto(int idFoto) {
		this.idFoto = idFoto;
	}

	public Foto(int idFoto, Docente docente, String nomRuta, Boolean blEstado) {
		this.idFoto = idFoto;
		this.docente = docente;
		this.nomRuta = nomRuta;
		this.blEstado = blEstado;
	}

	@Id
	@Column(name = "id_foto", unique = true, nullable = false)
	public int getIdFoto() {
		return this.idFoto;
	}

	public void setIdFoto(int idFoto) {
		this.idFoto = idFoto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_docente")
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@Column(name = "nom_ruta", length = 50)
	public String getNomRuta() {
		return this.nomRuta;
	}

	public void setNomRuta(String nomRuta) {
		this.nomRuta = nomRuta;
	}

	@Column(name = "bl_estado")
	public Boolean getBlEstado() {
		return this.blEstado;
	}

	public void setBlEstado(Boolean blEstado) {
		this.blEstado = blEstado;
	}

}
