package pe.edu.sistemas.dao.domain;

// Generated 05/11/2016 12:55:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HorarioCurso generated by hbm2java
 */
@Entity
@Table(name = "horario_curso")
public class HorarioCurso implements java.io.Serializable {

	private int idHorarioCurso;
	private Docente docente;
	private Horario horario;
	private Curso curso;
	private String semestre;
	private String nomGrupo;
	private String nomTipoClase;
	private Boolean estado;
	private Set asistencias = new HashSet(0);

	public HorarioCurso() {
	}

	public HorarioCurso(int idHorarioCurso) {
		this.idHorarioCurso = idHorarioCurso;
	}

	public HorarioCurso(int idHorarioCurso, Docente docente, Horario horario,
			Curso curso, String semestre, String nomGrupo, String nomTipoClase,
			Boolean estado, Set asistencias) {
		this.idHorarioCurso = idHorarioCurso;
		this.docente = docente;
		this.horario = horario;
		this.curso = curso;
		this.semestre = semestre;
		this.nomGrupo = nomGrupo;
		this.nomTipoClase = nomTipoClase;
		this.estado = estado;
		this.asistencias = asistencias;
	}

	@Id
	@Column(name = "id_horario_curso", unique = true, nullable = false)
	public int getIdHorarioCurso() {
		return this.idHorarioCurso;
	}

	public void setIdHorarioCurso(int idHorarioCurso) {
		this.idHorarioCurso = idHorarioCurso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_docente")
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_horario")
	public Horario getHorario() {
		return this.horario;
	}

	public void setHorario(Horario horario) {
		this.horario = horario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_curso")
	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	@Column(name = "semestre", length = 20)
	public String getSemestre() {
		return this.semestre;
	}

	public void setSemestre(String semestre) {
		this.semestre = semestre;
	}

	@Column(name = "nom_grupo", length = 5)
	public String getNomGrupo() {
		return this.nomGrupo;
	}

	public void setNomGrupo(String nomGrupo) {
		this.nomGrupo = nomGrupo;
	}

	@Column(name = "nom_tipo_clase", length = 5)
	public String getNomTipoClase() {
		return this.nomTipoClase;
	}

	public void setNomTipoClase(String nomTipoClase) {
		this.nomTipoClase = nomTipoClase;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horarioCurso")
	public Set getAsistencias() {
		return this.asistencias;
	}

	public void setAsistencias(Set asistencias) {
		this.asistencias = asistencias;
	}

}
