package pe.edu.sistemas.dao.domain;

// Generated 05/11/2016 12:55:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol")
public class Rol implements java.io.Serializable {

	private int idRol;
	private String nomRol;
	private Set usuarios = new HashSet(0);

	public Rol() {
	}

	public Rol(int idRol) {
		this.idRol = idRol;
	}

	public Rol(int idRol, String nomRol, Set usuarios) {
		this.idRol = idRol;
		this.nomRol = nomRol;
		this.usuarios = usuarios;
	}

	@Id
	@Column(name = "id_rol", unique = true, nullable = false)
	public int getIdRol() {
		return this.idRol;
	}

	public void setIdRol(int idRol) {
		this.idRol = idRol;
	}

	@Column(name = "nom_rol", length = 30)
	public String getNomRol() {
		return this.nomRol;
	}

	public void setNomRol(String nomRol) {
		this.nomRol = nomRol;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "rols")
	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

}
