package pe.edu.sistemas.dao.domain;

// Generated 05/11/2016 12:55:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario")
public class Usuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idUsuario;
	private String nomUsuario;
	private String password;
	private Set rols = new HashSet(0);

	public Usuario() {
	}

	public Usuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Usuario(int idUsuario, String nomUsuario, String password, Set rols) {
		this.idUsuario = idUsuario;
		this.nomUsuario = nomUsuario;
		this.password = password;
		this.rols = rols;
	}

	@Id
	@Column(name = "id_usuario", unique = true, nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "nom_usuario", length = 30)
	public String getNomUsuario() {
		return this.nomUsuario;
	}

	public void setNomUsuario(String nomUsuario) {
		this.nomUsuario = nomUsuario;
	}

	@Column(name = "password", length = 64)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "usuario_rol", joinColumns = { @JoinColumn(name = "id_usuario", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_rol", nullable = false, updatable = false) })
	public Set getRols() {
		return this.rols;
	}

	public void setRols(Set rols) {
		this.rols = rols;
	}

}
